async function main() {
    try {



    }
    catch (error) {

    }
}


main().catch(error => {
    console.error('An error occurred:', error);
    process.exit(1);
});